### ISSUE TITLE
Instalation problem

### ISSUE THREAD

**Issue by Kamil93** [ddopson/node-segfault-handler#22]
FreeBSD

npm install segfault-handler
npm WARN package.json db-mysql@0.7.6 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
npm http GET https://registry.npmjs.org/segfault-handler
npm http 200 https://registry.npmjs.org/segfault-handler
npm WARN package.json segfault-handler@0.2.4 No repository field.
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/bindings
npm ERR! Error: No compatible version found: bindings@'^1.2.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.3.0","0.4.0","1.0.0","1.1.0","1.1.1","1.2.0","1.2.1"]
npm ERR!     at installTargetsError (/usr/home/xxx/.nvm/v0.8.25/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /usr/home/xxx/.nvm/v0.8.25/lib/node_modules/npm/lib/cache.js:641:10
npm ERR!     at saved (/usr/home/xxx/.nvm/v0.8.25/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System FreeBSD 10.1-RELEASE
npm ERR! command "/home/xxx/.nvm/v0.8.25/bin/node" "/home/xxx/.nvm/v0.8.25/bin/npm" "install" "segfault-handler"
npm ERR! cwd /usr/home/xxx
npm ERR! node -v v0.8.25
npm ERR! npm -v 1.2.30
npm http 200 https://registry.npmjs.org/nan
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/home/xxx/npm-debug.log
npm ERR! not ok code 0

**Comment by No9** [comment]
Weird that looks like npm can't find 1.2.1 but that is the latest version. 

Can you ```npm -v``` and put the output here to be sure you are on a version that support the `^` operator?

Thanks

**Comment by Kamil93** [comment]
[xxx@sv]:<~>$ npm -v
1.2.30

**Comment by No9** [comment]
wow Last commit there was from 2 years ago! 
https://github.com/npm/npm/tree/v1.2.30 

If you run ```node -v``` and the version is less than v0,10 I strongly suggest that you upgrade that too. 

If you are v0.10 or above then upgrade npm 

``` npm install -g npm ``` as instructed here 

https://github.com/npm/npm/issues/1840#issuecomment-57648865 

Can I ask where you got this install of node and npm from?

**Comment by Kamil93** [comment]
On some shared shell hosting.

I use node v0.8.x because of module db-mysql. With v0.10 you can't install it. So I'm in node 0.8. And benchmarks says that 0.8 is better for sending UTF8 data, this is the second reason.

http://nodejs.org/benchmarks-v0.10-vs-v0.8/

If the reason of SIGSEGV will be in db-mysql (and this is the only native module I use) then probably I will change node to v0.10.

Anyway, thanks! :)

**Comment by No9** [comment]
@Kamil93  OK So I am running FreeBSD 11 CURRENT 
node 4.4.2
npm 2.1.4 
and this is no longer an issue so I am going to close it
Please re-open if you think there is an issue with FreeBSD support.
