### ISSUE TITLE
Registry Free Dll for a Com DLL

### ISSUE THREAD

**Issue by kiranjoshy123** [ddopson/node-segfault-handler#23]
I am new to node-gyp and facing a serious problem and stuck in the middle.

Issue:-
We are using a node server to load a normal C++ DLL which internally loads a COM DLL.
The workflow is like the front-end javascript will call the node server which will call the DLL functionality. The DLL uses a third party COM DLL to achieve the functionality.
javascript->node->Normal DLL->COM DLL

Since the third party DLL is a COM DLL, it needs to be registered. But we had a requirement not to register the same.By following the instructions in the below link we can achieve this. 
http://blogs.msdn.com/b/yvesdolc/archive/2008/05/09/native-manifests-let-s-do-com-and-forget-the-registry.aspx
i.e. we need to add some settings in the third party COM dll and the DLL/Exe which loads the COM dll.

This will work fine if the DLL is loaded by an exe. But in our case, it is loaded by node server.
Let the COM dll already had the settings to make it registry free. Hence if the com DLL is loaded by another DLL, which is loaded by an exe, then the setting need to be done in the EXE.
Exe->Normal DLL->COM DLL

But in our case the workflow is as below.
node->Normal DLL->COM DLL

Hence we need to add the settings in the node and buid it.
Settings needed to be added is "type='x64' name='COM_DLL_NAME' version='1.0.0.0'".
We were able to build the node sever with the settings.

'msbuild_settings': {
      'Link': {
        'GenerateDebugInformation': 'true',
		'AdditionalManifestDependencies': "type='x64' name='COM_DLL_NAME' version='1.0.0.0'",
     },
    },

But the COM dll is not loaded. i.e. cocreateInstance of the COM DLL is failing.
Any help will be appreciated.

**Comment by No9** [comment]
Hi @kiranjoshy123 I don't think this is an issue for segfault handler. From your opening statement did you intend to post to https://github.com/TooTallNate/node-gyp ? 

Given this is an windows integration issue you may find a solution/more support here 
https://github.com/tjanczuk/edge

**Comment by kiranjoshy123** [comment]
Thank you. 
The issue was related to node-gyp. So I will post it there.
