### ISSUE TITLE
Compiling for io.js 3.x / Node 4.x

### ISSUE THREAD

**Issue by ide** [ddopson/node-segfault-handler#27]
nan needs to be updated to 2.x. Requires some work but I believe it's somewhat of a straightforward upgrade.

**Comment by No9** [comment]
I think that is already done. 
https://github.com/ddopson/node-segfault-handler/pull/26 
Just waiting for a merge from @ddopson ?

**Comment by ddopson** [comment]
Hey, lemme look

**Comment by ddopson** [comment]
Merged.  Because I don't use node right now, I'm not great at tracking issues on this project.
No9, I'm going to add you as a maintainer on this project.
