### ISSUE TITLE
npm version doesn't include PR #5

### ISSUE THREAD

**Issue by bryanlarsen** [ddopson/node-segfault-handler#8]
I had the issue fixed by PR #5 when I installed via npm install segfault-handler.  Installing from git worked (npm install git://github.com/ddopson/node-segfault-handler.git)

I would guess that bumping the version number and pushing will fix the problem.

**Comment by No9** [comment]
Hi @bryanlarsen  
Following https://github.com/ddopson/node-segfault-handler/pull/26 I think we are good in npm
If not then please feel free to open another issue
