### ISSUE TITLE
Symbol segfault_handler_native_module not found

### ISSUE THREAD

**Issue by Koromori** [ddopson/node-segfault-handler#9]
Attempting to require this module gives the error: `Symbol segfault_handler_native_module not found.` This is from an empty project. node v0.10.25, linux mint 16.

Incidentally, while installing it I saw the warning:

	make: Entering directory `/home/koromori/test/node_modules/segfault-handler/build'
	  CXX(target) Release/obj.target/segfault-handler-native/src/segfault-handler.o
	../src/segfault-handler.cpp: In function ‘void segfault_handler(int, siginfo_t*, void*)’:
	../src/segfault-handler.cpp:39:33: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
	   if(fd > 0) write(fd, sbuff, n);
	                                 ^
	../src/segfault-handler.cpp:40:29: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
	   write(STDERR_FD, sbuff, n);

**Comment by No9** [comment]
@japrescott @panuhorsmalahti @Koromori we are now on 2.5 on npm https://www.npmjs.com/package/segfault-handler 
So I am going to close this off.
If here is anything else please open another issue
